### PR TITLE
Update members.csv

### PR DESCRIPTION
**Pull request by mcoudoures**

### CODE REVIEW

**Comment by bschoenfeld** [comment]
Nice work

**Comment by bschoenfeld** [comment]
It looks like you put the wrong name for your Github user. Can you submit another pull request?

**Comment by mcoudoures** [comment]
Sorry about that. It’s fixed.

Michael Coudoures
Computer Engineering
Class of 2018
Virginia Tech

From: Ben Schoenfeld
Sent: ‎Wednesday‎, ‎October‎ ‎28‎, ‎2015 ‎10‎:‎46‎ ‎AM
To: CodeforNRV/codefornrv
Cc: mcoudoures

It looks like you put the wrong name for your Github user. Can you submit another pull request?

**Comment by bschoenfeld** [comment]
Did you submit another pull request?

**Comment by mcoudoures** [comment]
I may have accidentally not submitted a pull request. I committed the change and submitted a pull request this time. It is showing up as open for the document.

Michael Coudoures
Computer Engineering
Class of 2018
Virginia Tech

From: Ben Schoenfeld
Sent: ‎Thursday‎, ‎October‎ ‎29‎, ‎2015 ‎5‎:‎59‎ ‎PM
To: CodeforNRV/codefornrv
Cc: mcoudoures

Did you submit another pull request?

**Pull request merged**
